#!/bin/bash

    #Author : Excel
    #Date : 30-Jan-2023

## ---------- script that Install some packages in Linux -----------------
#This works only on centos-7 servers

echo "switching to root user"
sudo-su
echo "switched to root user"

yum install finger -y 
yum install curl -y 
yum install zip -y 
yum install vim -y 
yum install net-tools -y
yum install git -y 
yum install httpd-y 
systemctl start httpd  
systemctl enable httpd 
systemctl status httpd
yum install epel-release -y


#end